### ISSUE TITLE
Support Custom Base URL

### ISSUE THREAD

**Issue by osterman** [cloudposse-archives/helm-s3#1]
## what
* Support custom base URL

## why
* So we can use `helm-s3` to manage our public repo https://charts.cloudposse.com

## todo
- [ ] Rebase this PR https://github.com/hypnoglow/helm-s3/pull/46
- [ ] Open PR against hypnoglow/helm-s3
- [ ] Add codefresh build and attach helm-s3 binary as release asset (maybe second PR)

**Comment by osterman** [comment]
@alebabai you should be able to use this target to push artifacts https://github.com/cloudposse/build-harness/blob/master/modules/github/Makefile.release#L26

**Comment by osterman** [comment]
Closing: this repository is being archived.
